import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Box,ChartNoAxesCombined,ChevronRight,Download,FlaskConical,FolderOpen,Info,Layers,Maximize,Pause,Play,Radio,RotateCcw,ShieldCheck,SkipBack,Thermometer,TriangleAlert,Zap} from 'lucide-react';
import Engine from './Engine';
import FaultLab from './FaultLab';
import VibrationPanel, {type VibrationSettings} from './VibrationPanel';
import {sensorStates} from './sensor-state';
import Chart from './Chart';
import type {Overview,Replay,Sample,Sensor} from './types';

const signalNames:Record<string,string>={propeller_rpm:'Propeller speed',boost_pa:'Manifold pressure',ambient_pa:'Ambient pressure',oil_pressure_pa:'Oil pressure',rail_pressure_pa:'Rail pressure',power_lever_pct:'Power lever',coolant_c:'Coolant temperature',intake_c:'Intake air temperature',battery_v:'Bus voltage',fuel_pressure_pa:'Fuel supply pressure',gearbox_oil_c:'Gearbox oil temperature',oil_c:'Oil temperature',prop_duty_pct:'Prop actuator duty',engine_status:'Engine status',oil_level_mm:'Oil level',engine_load_pct:'Engine load'};
const fmt=(v:number|null|undefined,dec=1)=>v==null?'—':v.toLocaleString('en-US',{maximumFractionDigits:dec});
const clock=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const api=(p:string)=>window.aero.api('GET',p);

function Metric({name,value,unit,quality,accent=false}:{name:string,value:number|null|undefined,unit:string,quality:string,accent?:boolean}){return <div className={'metric '+(accent?'accent':'')}><div className="eyebrow">{name}</div><div className="metric-value">{fmt(value)} <span>{unit}</span></div><div className={'quality '+(value==null?'missing':'')}><i/>{value==null?'Unavailable':quality}</div></div>;}

function Bench(){const [power,setPower]=useState(60),[ambient,setAmbient]=useState(25),[cooling,setCooling]=useState(1),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const run=async()=>{setBusy(true);setError('');try{setResult(await window.aero.api('POST','/v1/simulate/bench',{initial_c:ambient,segments:[{duration_s:600,shaft_power_kw:power,ambient_c:ambient,ambient_pa:101325,cooling_factor:cooling}]}));}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section className="bench-page"><div className="page-title"><div><div className="eyebrow">EXPERIMENT WORKSPACE</div><h1>Thermal bench</h1><p>Explore a reduced-order model. These results are simulated, not measured.</p></div><span className="badge amber">UNCALIBRATED MODEL</span></div><div className="bench-layout"><div className="panel controls-panel"><h3>Scenario inputs</h3><p className="muted">Ten-minute, constant-input demonstration.</p><label>Assumed shaft power <b>{power} kW</b><input type="range" min="0" max="123" value={power} onChange={e=>setPower(+e.target.value)}/></label><label>Ambient temperature <b>{ambient} °C</b><input type="range" min="-20" max="50" value={ambient} onChange={e=>setAmbient(+e.target.value)}/></label><label>Relative cooling <b>{cooling.toFixed(1)}×</b><input type="range" min="0.2" max="1.5" step="0.1" value={cooling} onChange={e=>setCooling(+e.target.value)}/></label><button className="primary" onClick={run} disabled={busy}><FlaskConical size={16}/>{busy?'Calculating…':'Run simulation'}</button>{error&&<p className="error">{error}</p>}<div className="notice">Assumed heat capacities, efficiency and cooling coefficients. Not an engine operating envelope or flight-performance model.</div></div><div className="panel simulation-result"><div className="panel-heading"><h3>Temperature response</h3><span className="muted">°C · simulated</span></div>{result?<><Chart height={340} unit="°C" labels={result.samples.map((r:any)=>r.time_s)} series={[{name:'Coolant',color:'#43dac3',data:result.samples.map((r:any)=>r.coolant_c)},{name:'Oil',color:'#e4a661',data:result.samples.map((r:any)=>r.oil_c)}]}/><div className="simulation-stats"><Metric name="Final coolant" value={result.samples.at(-1).coolant_c} unit="°C" quality="Simulated"/><Metric name="Final oil" value={result.samples.at(-1).oil_c} unit="°C" quality="Simulated"/><Metric name="Fuel flow" value={result.samples.at(-1).synthetic_fuel_flow_l_h} unit="L/h" quality="Assumed efficiency"/></div></>:<div className="empty-state"><FlaskConical size={38}/><h3>Your experiment starts here</h3><p>Set the inputs and run a simulation to inspect the thermal response.</p></div>}</div></div></section>;
}

export default function App(){
 const [tab,setTab]=useState('twin'),[sessions,setSessions]=useState<Replay[]>([]),[sid,setSid]=useState(''),[overview,setOverview]=useState<Overview|null>(null),[samples,setSamples]=useState<Sample[]>([]),[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[mode,setMode]=useState('assembled'),[animate,setAnimate]=useState(true),[motionSlowdown,setMotionSlowdown]=useState(1),[reset,setReset]=useState(0),[selected,setSelected]=useState('Sensor_BPS1'),[busy,setBusy]=useState('Loading engine workspace…'),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [vibration,setVibration]=useState<VibrationSettings>({enabled:!window.matchMedia('(prefers-reduced-motion: reduce)').matches,roughness:.6,gain:60});
 const [ready,setReady]=useState(false);const requestID=useRef(0);
 const session=sessions.find(s=>s.id===sid);const sample=samples.find(s=>s.index===index);const quality=session?.source==='fault_injected'?'Injected':session?.source==='synthetic'?'Simulated':'Recorded';
 const selectedSensor=sample?.cad.bindings.find(s=>s.object===selected);
 const loadSessions=useCallback(async(preferred?:string)=>{const items=await api('/v1/desktop/sessions');setSessions(items);setSid(preferred||items[0]?.id||'');},[]);
 useEffect(()=>{let cancelled=false;(async()=>{try{await api('/health');if(!cancelled){await loadSessions();setReady(true);setBusy('');}}catch(e){if(!cancelled){setError(String(e));setBusy('');}}})();return()=>{cancelled=true;};},[loadSessions]);
 useEffect(()=>{if(!sid)return;let cancelled=false;requestID.current++;setPlaying(false);setIndex(0);setSamples([]);setOverview(null);setBusy('Loading session…');Promise.all([api(`/v1/desktop/sessions/${sid}/overview`),api(`/v1/desktop/sessions/${sid}/window?start=0&limit=120`)]).then(([ov,win])=>{if(!cancelled){setOverview(ov);setSamples(win.items);setBusy('');}}).catch(e=>{if(!cancelled){setError(String(e));setBusy('');}});return()=>{cancelled=true;};},[sid]);
 useEffect(()=>{if(!sid||sample||busy)return;const id=++requestID.current;api(`/v1/desktop/sessions/${sid}/window?start=${Math.max(0,index-30)}&limit=120`).then(r=>{if(id===requestID.current)setSamples(r.items);}).catch(e=>{setError(String(e));setPlaying(false);});},[index,sid,sample,busy]);
 useEffect(()=>{if(!playing||!session||!sample)return;const timer=setInterval(()=>setIndex(i=>{if(i>=session.count-1){setPlaying(false);return i;}return i+1;}),1000/speed);return()=>clearInterval(timer);},[playing,speed,session,sample]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
 const importCSV=async()=>{setPlaying(false);setBusy('Choose a CSV. Import analysis may take a few seconds…');setError('');try{const s=await window.aero.importCSV();if(s){await loadSessions(s.id);setToast(`Imported ${s.count.toLocaleString()} records`);}}catch(e){setError(String(e));}finally{setBusy('');}};
 const createScenario=async(result:Replay)=>{setPlaying(false);setMode('cutaway');setAnimate(true);setTab('twin');await loadSessions(result.id);setToast('Experimental replay created; source unchanged. Press Play or Replay fault onset.');};
 const exportReport=async()=>{if(!sid)return;try{if(await window.aero.exportReport(sid))setToast('Research report exported');}catch(e){setError(String(e));}};
 const points=overview?.points||[];const labels=useMemo(()=>points.map(p=>String(p.index)),[points]);
 const v=sample?.values||{};const status=sample?.analysis.status;const anomaly=sample?.persistent_anomaly;const candidate=sample?.analysis.candidate_anomaly;
 const chartSignal=selectedSensor?.readings[0]?.canonical_signal||'boost_pa';const pressure=chartSignal.endsWith('_pa');
 const selectedSeries=useMemo(()=>[{name:signalNames[chartSignal]||chartSignal,color:'#46dcc2',data:points.map(p=>p.values[chartSignal]==null?null:p.values[chartSignal]!/(pressure?100000:1))}],[points,chartSignal,pressure]);
 return <div className="app" data-app-ready={ready&&Boolean(sample)}><aside className="rail"><div className="brand-mark">A<span/></div><button className={tab==='twin'?'active':''} onClick={()=>setTab('twin')} title="Digital twin"><Box/><span>Assembly</span></button><button className={tab==='trends'?'active':''} onClick={()=>setTab('trends')} title="Trend analysis"><ChartNoAxesCombined/><span>Signals</span></button><button className={tab==='bench'?'active':''} onClick={()=>setTab('bench')} title="Thermal bench"><FlaskConical/><span>Bench</span></button><div className="rail-spacer"/><button className={tab==='about'?'active':''} onClick={()=>setTab('about')} title="About and limitations"><Info/><span>Notes</span></button><span className="rail-version">v0.1</span></aside>
 <div className="main-shell"><header><div className="brand"><b>AEROTRACE<span> / </span></b><span>POWERPLANT RESEARCH</span></div><div className="header-right"><span className="local-status"><i/>{ready?(window.aero.publicDemo?'Synthetic demo ready':'Local analytics ready'):'Connecting'}</span><span className="divider"/><span className="badge">SIH / 2026</span></div></header>
 <main><div className="workspace-toolbar"><div className="breadcrumbs">WORKSPACE <ChevronRight size={13}/><span>AE300 / E4</span></div><div className="actions">{!window.aero.publicDemo&&<button onClick={importCSV} disabled={!!busy}><FolderOpen size={15}/>Import CSV</button>}<button onClick={exportReport} disabled={!sid||!!busy}><Download size={15}/>Export report</button></div></div>
 {error&&<div className="error-banner" role="alert"><TriangleAlert size={17}/><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}{busy&&<div className="loading-bar">{busy}</div>}
 {tab==='bench'?<Bench/>:tab==='about'?<section className="about-page panel"><span className="badge">AEROTRACE 0.1</span><h1>Research notes</h1><p>An AE300 research workspace combining a reconstructed 619-solid engine model with contextual telemetry analysis.</p><div className="about-grid"><article><h3>What is available</h3><p>16 recorded-channel inputs, 32 CAD bindings, causal replay, physics estimates, contextual anomaly evidence and an illustrative thermal bench.</p></article><article><h3>What is not established</h3><p>OEM-complete CAD, confirmed fault diagnoses, calibrated remaining useful life, flight readiness or failure probabilities. The model was trained on unlabelled public examples.</p></article><article><h3>{window.aero.publicDemo?'Public demonstration':'Data stays on this computer'}</h3><p>{window.aero.publicDemo?'Only freshly generated synthetic telemetry and precomputed scenario analyses are published. No log uploads, ECU commands or live hardware connection.':'Imported logs and analysis are stored locally. No cloud upload, ECU commands or live hardware connection. The private backend starts and stops with this application.'}</p></article><article><h3>Know your source</h3><p>The included demo is generated, not an actual engine run. Imported CSVs are recorded inputs whose decoder and engine identity must still be verified. Missing values are never shown as healthy.</p></article></div></section>:<>
 <div className="page-title"><div><div className="eyebrow">{tab==='twin'?'01 / POWERPLANT':'03 / SIGNAL HISTORY'}</div><h1>{tab==='twin'?'AE300 / Engine observatory':'Signals & evidence'}</h1><p>Four-cylinder compression-ignition engine <span className="dot">·</span> 1.991 L <span className="dot">·</span> 1.69 reduction</p></div><div className="session-select"><label>ACTIVE SESSION <span className={'badge '+(session?.source==='synthetic'?'amber':'')}>{session?.source==='fault_injected'?'FAULT INJECTED':session?.source==='synthetic'?'SIMULATED':'REPLAY'}</span></label><select aria-label="Active session" value={sid} onChange={e=>setSid(e.target.value)}>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div>
 <div className="metrics"><Metric name="Propeller speed" value={v.propeller_rpm} unit="rpm" quality={quality} accent/><Metric name="Engine load" value={v.engine_load_pct} unit="%" quality={quality}/><Metric name="Oil pressure" value={v.oil_pressure_pa==null?null:v.oil_pressure_pa/100000} unit="bar" quality={quality}/><Metric name="Coolant" value={v.coolant_c} unit="°C" quality={quality}/><Metric name="Bus voltage" value={v.battery_v} unit="V" quality={quality}/></div>
 {tab==='twin'?<div className="twin-grid"><section className="panel engine-panel"><div className="panel-heading"><div><Layers size={15}/><h3>Engine assembly</h3><span className="tag">619 SOLIDS</span></div><button className="icon-button" title="Reset camera" onClick={()=>setReset(r=>r+1)}><Maximize size={15}/></button></div><div className="model-tabs">{['assembled','cutaway','integration'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m==='integration'?'With electronics':m[0].toUpperCase()+m.slice(1)}</button>)}<select className="motion-speed" aria-label="CAD speed mode" value={motionSlowdown} onChange={e=>setMotionSlowdown(Number(e.target.value))}><option value={1}>Real speed · 1:1</option><option value={120}>Study · 1/120</option></select><label className="motion-toggle"><input type="checkbox" checked={animate} onChange={e=>setAnimate(e.target.checked)}/>RPM-linked motion</label></div><div className="viewport"><Engine mode={mode} selected={selected} onSelect={setSelected} animate={animate} reset={reset} playing={playing} speed={speed} slowdown={motionSlowdown} crankRpm={sample?.physics.crankshaft_rpm?.value} phase={(sample?.motion?.display_total_deg??sample?.motion?.display_phase_deg??0)*(sample?.motion?.slowdown??120)/motionSlowdown} sampleKey={`${sid}:${index}`} objectStates={sensorStates(sample)} vibration={vibration}/><div className="viewport-note"><span className="crosshair">+</span><span>AE300 / RECONSTRUCTED GEOMETRY<br/><small>{!animate?'Motion disabled':!sample?'Waiting for telemetry':v.propeller_rpm==null?'Motion unavailable · RPM missing':v.propeller_rpm===0?'Engine stopped · zero RPM':playing?(motionSlowdown===1?'Real RPM × replay speed · screen may alias fast rotation':'Study mode · 1/120 RPM × replay speed'):'Paused · press Play for RPM-linked motion'}</small></span></div><span className="axis-badge">3D / m</span></div><div className="engine-footer"><span><i className="teal-dot"/>Selectable CAD components</span><span>Sensor colours: amber injected · red deviation · grey missing</span></div></section>
 <aside className="detail-column"><section className="panel state-panel"><div className="panel-heading"><h3>Analysis state</h3><Activity size={16}/></div><div className={'state-title '+(anomaly||candidate?'warning':status==='scored'?'good':'muted')}><span className="state-dot"/>{!sample?'Loading…':anomaly?'Persistent anomaly':candidate?'Transient anomaly candidate':status==='scored'?'Within learned reference':status?.replaceAll('_',' ')}</div><div className="alignment"><span>Reference alignment</span><strong>{fmt(sample?.reference_alignment_index,0)}<small>/100</small></strong></div><div className="meter"><span style={{width:`${sample?.reference_alignment_index||0}%`}}/></div><p className="tiny">Model agreement, not percent health or a safety clearance.</p><div className="state-pair"><span>Operating regime</span><b>{sample?.analysis.regime||'—'}</b></div><div className="state-pair"><span>Remaining useful life</span><b className="muted">Not validated</b></div></section>
 <section className="panel sensor-panel"><div className="panel-heading"><h3>Component inspector</h3><Radio size={16}/></div><select aria-label="Sensor inspector" value={selectedSensor?.object||''} onChange={e=>setSelected(e.target.value)}><option value="">Selected component</option>{sample?.cad.bindings.map((s,i)=><option key={i} value={s.object}>{s.sensor_id.replaceAll('_',' ')}</option>)}</select><h2>{selectedSensor?.sensor_id.replaceAll('_',' ')||selected.replaceAll('_',' ')}</h2><div className="sensor-readings">{selectedSensor?.readings.length?selectedSensor.readings.map(r=><div key={r.canonical_signal}><span>{signalNames[r.canonical_signal]}</span><b>{fmt(r.value,r.unit==='Pa'?0:1)} <small>{r.unit}</small></b><em className={r.value==null?'missing':''}>{r.value==null?r.quality:quality}</em></div>):<div className="unavailable"><span>Measurement unavailable</span><p>{selectedSensor?'Not recorded in the base log. No value has been invented.':'Geometry selected. Choose a sensor to inspect its recorded signal.'}</p></div>}</div><p className="tiny">{selectedSensor?.source_scope||'Reconstructed geometry; not a manufacturing definition.'}</p></section></aside></div>:<div className="trends-grid"><section className="panel"><div className="panel-heading"><h3>Thermal channels</h3><span className="muted">{quality}</span></div><Chart labels={labels} cursor={index} unit="°C" height={280} series={['coolant_c','oil_c','gearbox_oil_c'].map((k,i)=>({name:signalNames[k],color:['#43dac3','#e5ac6a','#a99bed'][i],data:points.map(p=>p.values[k])}))}/></section><section className="panel"><div className="panel-heading"><h3>Pressure channels</h3><span className="muted">{quality}</span></div><Chart labels={labels} cursor={index} unit="bar" height={280} series={['boost_pa','oil_pressure_pa','fuel_pressure_pa'].map((k,i)=>({name:signalNames[k],color:['#43dac3','#e5ac6a','#95abe8'][i],data:points.map(p=>p.values[k]==null?null:p.values[k]!/100000)}))}/></section></div>}
 {tab==='twin'&&<VibrationPanel rpm={sample?.physics.crankshaft_rpm?.value} playing={playing&&animate} speed={speed} settings={vibration} onChange={setVibration}/>}
 <FaultLab sessions={sessions} session={session} sample={sample} onCreated={createScenario} onSeek={(i,play)=>{setIndex(i);setPlaying(play);}}/>
 <div className="lower-grid"><section className="panel trace-panel"><div className="panel-heading"><h3>{tab==='twin'?(signalNames[chartSignal]||'Selected signal'):'Residual anomaly score'}</h3><span className="muted">{tab==='twin'?quality:'Model output'} · index along session</span></div><Chart labels={labels} cursor={index} unit={tab==='twin'?(pressure?'bar':selectedSensor?.readings[0]?.unit||''):'ratio'} series={tab==='twin'?selectedSeries:[{name:'Score / threshold',color:'#e5ac6a',data:points.map(p=>p.ratio)}]}/></section><section className="panel evidence-panel"><div className="panel-heading"><h3>Event evidence</h3><span className="tag">{overview?.events.length||0} INTERVALS</span></div><div className="event-list">{sample?.warnings.some(w=>w.type==='data_quality')&&<div className="event"><TriangleAlert size={16}/><div><b>Data quality warning</b><p>One or more channels are unavailable.</p></div></div>}{overview?.events.length?overview.events.slice(0,20).map((e,i)=><button key={i} className="event" onClick={()=>{setPlaying(false);setIndex(e.start);}}><TriangleAlert size={16}/><div><b>{signalNames[e.signals[0]]||e.signals[0]||'Contextual deviation'}</b><p>Persistent anomaly · review required</p></div><span>{clock(e.start)}</span></button>):<div className="no-events"><ShieldCheck size={24}/><p>No persistent intervals in this session.<br/><small>This does not establish engine health.</small></p></div>}</div></section></div>
 <section className="replay-bar"><div className="transport"><button className="icon-button" title="Restart replay" onClick={()=>{setIndex(0);setPlaying(false);}}><SkipBack size={17}/></button><button className="play-button" title={playing?'Pause replay':'Play replay'} onClick={()=>{if(session&&index>=session.count-1)setIndex(0);setPlaying(p=>!p);}} disabled={!sample}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><select aria-label="Replay speed" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[1,2,5,10].map(s=><option key={s} value={s}>{s}×</option>)}</select></div><span className="replay-time">{clock(index)}</span><input aria-label="Replay position" type="range" min="0" max={(session?.count||1)-1} value={index} onChange={e=>{setPlaying(false);setIndex(+e.target.value);}}/><span className="muted">{clock((session?.count||1)-1)}</span><div className="replay-stamp"><b>{sample?new Date(sample.timestamp).toISOString().slice(11,19):'—'} UTC</b><small>{session?.source==='fault_injected'?'FAULT EXPERIMENT':session?.source==='synthetic'?'SYNTHETIC TIMELINE':'HISTORICAL REPLAY'} · 1 Hz</small></div></section>
 </>}
 </main><footer><span><ShieldCheck size={12}/>Offline research workspace · no ECU control</span><span>Estimates ≠ measurements <span className="dot">·</span> No airworthiness decisions</span></footer></div>{toast&&<div className="toast">{toast}</div>}</div>;
}
